# Generated by Django 2.2.3 on 2020-01-15 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pict', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='works',
            name='mainPic',
            field=models.ImageField(default='', upload_to='mPic', verbose_name='Картинка'),
        ),
    ]
