# Generated by Django 2.2.3 on 2020-04-21 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pict', '0002_works_mainpic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='works',
            name='mainPic',
            field=models.ImageField(default='', upload_to='mPic', verbose_name='Главная картинка'),
        ),
    ]
